server/basket/urls.py
from django.urls import path
from .views import basket_view


app_name = 'basket'

urlpatterns = [
    path('', basket_view, name='basket'),
]

server/catalog/urls.py
from django.urls import path
from catalog.views import (
    CatalogView, ProductDeleteView, ProductUpdateView,
    ProductDetailView, ProductCreateView
    )

from catalog.views import (
    CatalogView, ProductDeleteView, ProductUpdateView,
    ProductDetailView, ProductCreateView, CategoryView
    )

app_name = 'catalog'


urlpatterns = [
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('catalog/category/<int:pk>/', CategoryView.as_view(), name='category'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('catalog/update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('catalog/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('catalog/detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp
from rest_framework.routers import DefaultRouter
from catalog.api import CatalogViewSet, ProductViewSet
from basket.api import PurchaseViewSet

router = DefaultRouter()
router.register('categories', CatalogViewSet)
router.register('products', ProductViewSet)
router.register('basket', PurchaseViewSet)


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls, name='admin'),
    path('api/', include((router.urls, 'api'))),
    path('', include('catalog.urls')),
    path('', include('accounts.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('basket/', include('basket.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/basket/models.py
from django.db import models
from functools import reduce


# Create your models here.


class Purchase(models.Model):
    user = models.ForeignKey(
        'accounts.Account',
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    is_active = models.BooleanField(
        default=False
    )

    @property
    def cost(self):
        return reduce(
            lambda total, itm: total + itm.product.price,
            self.items.all(),
            0
        )

    @property
    def count(self):
        return reduce(
            lambda total, itm: total + itm.value,
            self.items.all(),
            0
        )

    def __str__(self):
        full_name = self.user.get_full_name
        title = full_name if full_name else self.user.username
        return f'{title} {self.created.strftime("%Y-%m-%d %H:%M")}'


class PurchaseItem(models.Model):
    purchase = models.ForeignKey(
        Purchase,
        on_delete=models.CASCADE,
        related_name='items'
    )
    product = models.ForeignKey(
        'catalog.ProductDetail',
        on_delete=models.CASCADE
    )
    value = models.IntegerField(
    )

    def __str__(self):
        return self.product.name

server/basket/routes.py
from django.urls import path
from .views import PurchaseCreateView


app_name = 'basket_api'

urlpatterns = [
    path('create/', PurchaseCreateView.as_view(), name='create'),
]

server/basket/views.py
import json
from functools import reduce
from django.apps import apps
from django.db.models import Q
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (View, DetailView, ListView)
from .models import Purchase, PurchaseItem


def basket_view(request):
    return render(request, 'basket/basket.html')


class PurchaseCreateView(LoginRequiredMixin, View):
    login_url = ''
    product_model = apps.get_model('catalog', 'ProductDetail')

    def post(self, request):
        data = json.loads(request.body)

        product_list = self.product_model.objects.filter(
            reduce(
                lambda store, key: store | Q(pk=key),
                data.keys(),
                Q()
            )
        )

        obj = Purchase.objects.create(
            user=request.user,
        )

        for product in product_list:
            obj.items.create(
                product=product,
                value=data[str(product.id)],
            )

        return JsonResponse(
            {
                'success_url': reverse(
                    'cart:detail',
                    kwargs={'pk': obj.id}
                )
            }
        )

server/basket/templates/basket/basket.html
{% extends 'server/master.html' %}
{% load static %}

<title>
    {% block page_title %}
    {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
    {% csrf_token %}
    <h3>Корзина</h3>
    <form class="form-inline">
        <div class="form-group mb-2">
            <input type="text" readonly class="form-control-plaintext" value="Наименование">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" readonly class="form-control-plaintext" value="Количество">
        </div>
    </form>
    <div class="product-list"></div>
    <div class="control-panel"></div>
    {% endblock %}
</div>
{% block page_js %}
<script src="{% static 'js/counter.js' %}"></script>
<script src="{% static 'js/basket/submit.js' %}"></script>
<script src="{% static 'js/basket/items.js' %}"></script>

<script>
    const emptyText = 'Корзина пуста';
    const mainUrl = '{% url "catalog:catalog" %}';
    const createPurchaseUrl = '{% url "catalog:catalog" %}';
    const tokenInput = document.querySelector('[name=csrfmiddlewaretoken]');
    const productsList = document.querySelector('.product-list');
    const controlPanlel = document.querySelector('.control-panel');
    const items = getLocalValue('products');
    const identityList = Object.keys(items);
    console.log(tokenInput)
    if (identityList.length <= 0) {
        productsList.appendChild(
            createEmptyMock(mainUrl, emptyText)
        );
    } else {
        const productsUrl = `{% url 'api:productdetail-list' %}?id__in=${identityList.join(',')}`;
        fetch(productsUrl)
            .then(response => response.json())
            .then(data => {
                data.results.map(
                    itm => productsList.innerHTML += renderItem(itm, items[itm.pk])
                )
            })

        controlPanlel.appendChild(
            createCartSubmit(createPurchaseUrl, tokenInput.value)
        );
    }
</script>
{% endblock %}

server/basket/templates/basket/list.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
    {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
    <h3>Корзина</h3>
    <form class="form-inline">
        <div class="form-group mb-2">
            <input type="text" readonly class="form-control-plaintext" value="Наименование">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" readonly class="form-control-plaintext" value="Количество">
        </div>
    </form>
    {% for item in results %}
    <form class="form-inline">
        <div class="form-group mb-2">
            <input type="text" readonly class="form-control-plaintext"value="{{item}}">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <input type="number" class="form-control" value="1">
        </div>
    </form>
    {% endfor %}
    <button type="submit" class="btn btn-primary mb-2">Оформить заказ</button>
    {% endblock %}
</div>